name = "film-worker"
main = "src/index.js"
compatibility_date = "2023-10-30"

# Disable the .dev html route as not needed for cron jobs
workers_dev = false

# Cron Triggers
[triggers]
#1 - at 11:45 every two days
#2 - at half past every 8th hour
crons = ["45 11 */2 * *","30 */8 * * *"]

# D1 Database
[[d1_databases]]
binding = "FILM_DB"
database_name = "film"
database_id = "e317e69c-1a54-4c06-b74c-eab352cc1aa4"
