name = "film-worker"
main = "src/index.js"
compatibility_date = "2023-10-30"

# Disable the .dev html route as not needed for cron jobs
workers_dev = false

# Allow node modules
node_compat = true

# Cron Triggers
[triggers]
#1 - at 11:05 every day
#2 - at half past every 8th hour
crons = ["5 11 * * *","30 */8 * * *","2 10 * * *"]

# D1 Database
[[d1_databases]]
binding = "FILM_DB"
database_name = "film"
database_id = "e317e69c-1a54-4c06-b74c-eab352cc1aa4"

